### ISSUE TITLE
Not working in Lambda

### ISSUE THREAD

**Issue by xuanhungptithcm** [photostructure/exiftool-vendored.js#101]
**Describe the bug**
It cannot be working in lambda, I have waited for 15 minutes, wait till lambda timeout, Can you show me your suggestion to fix it. After I used Lambda it work well in the server at EC2

**Environment (please complete the following information):**
 - OS and version: Lambda Linux
 - Node.JS version 14

**Comment by mceachen** [comment]
Apologies, but aws lambda isn't supported:

https://github.com/photostructure/exiftool-vendored.js/issues/69#issuecomment-562717252
