### ISSUE TITLE
Allow `write`'s WriteTags typing to be generic

### ISSUE THREAD

**Issue by dearsaturn** [photostructure/exiftool-vendored.js#103]
**Is your feature request related to a problem? Please describe.**
Tags written to a file don't necessarily have to be what's specified in `WriteTags`. See this example in use today:
```ts
await exifTool.write(
  path.join(localFileStoragePath, filename),
  // @ts-ignore
  Attrib: 'something',
  ['-overwrite_original']
);
```
`Attrib` is not a tag mentioned in the `WriteTags` TypeScript typing, so we use `@ts-ignore` to get TS to ignore the typing error we are causing here, despite `write` allowing the tag to actually get written to the file.

**Describe the solution you'd like**
Give `write` a generic argument that extends `WriteTags` shape, e.g.:
```ts
await exifTool.write<WriteTags & {Attrib: string}>(
  path.join(localFileStoragePath, filename),
  Attrib: 'something',
  ['-overwrite_original']
);
```

**Describe alternatives you've considered**
An alternative to the above proposal would be not requiring the generic to extend `WriteTags` at all, but I'm not sure that's a great idea. _(edited, forgot to fill this out)_

**Additional context**
~

**Comment by mceachen** [comment]
Thanks for the suggestion: I've added this to version 15.3.0 which I've just released.

**Comment by dearsaturn** [comment]
@mceachen thank you for the quick turnaround!
