### ISSUE TITLE
deleteAllTags (or write equivalent) throws an exception with "No success message: 0 image files updated", even though image is updated.

### ISSUE THREAD

**Issue by rolanday** [photostructure/exiftool-vendored.js#119]
**Describe the bug**

Hi Matt!

Here's issue that I'm stuck on .

deleteAllTags (or write equivalent) throws an exception with "No success message: 0 image files updated", even though image is updated.

image file: https://www.dropbox.com/s/jmvsm5zi7c84pkd/test.jpg?dl=0

**To Reproduce**

1. Download image at https://www.dropbox.com/s/jmvsm5zi7c84pkd/test.jpg?dl=0
2. List tags using ExifTool v12.49
3. Run code below to remove tags (update file path to actual location)
4. Note the error
5. List tags using ExifTool v12.49, and note (non-file) tags successfully delete

When I run `exiftool -all= test.jpg` from command line, I get no such error, even though my local copy of ExifTool matches vendor packaged pl version (both 12.49)

```
import { ExifTool } from "./ExifTool"

const exiftool = new ExifTool()
run().then(() => {
  console.log("done")
})

export async function run() {
  await exiftool.write("test.jpg", {}, [
    "-all=",
    "-overwrite_original",
  ])
  // note: deleteAllTags produces same result
  await exiftool.end(true)
}

// throws exception with error: "No success message: 0 image files updated"
```

**Expected behavior**

Expect same behavior from exiftool-vendored wrapper as using exiftool directly.

Exception thrown from:

```
protected parse(data: string, error: Error): void {
    // console.log(this.toString() + ".parse()", { data, error })
    if (error != null) throw error
    if (this.errors.length > 0) throw new Error(this.errors.join(";"))
    data = data.trim()
    if (successRE.exec(data) != null) {
      return
    } else {
      throw new Error("No success message: " + data)
    }
  }
```

... which also begs the question if should be an exception since no error object (just fail re test on data string).

Thanks!!

**Environment (please complete the following information):**
System/project setup from my end.

- MacOS
- Node v16.16.0

```
  "dependencies": {
     ...
    "exiftool-vendored": "^18.4.2",
  },

```

**Comment by mceachen** [comment]
Howdy! ExifTool is burping out a warning for that example image you provided:

```
$ exiftool -all=  -overwrite_original test/delete-test.jpg 
Warning: ICC_Profile deleted. Image colors may be affected - test/delete-test.jpg
    1 image files updated
```

The error we're looking at is due to this library trying to be "helpful": `taskRetries` defaults to 1, and we _retry_ write operations. The first time it fails due to the ICC_Profile deletion, and the second time it fails because the second write is a no-op.

So! What to do?

1. Add "ignorable" errors to the config. It's what PhotoStructure has already, I can just move the code here.

2. Only retry read ops. Retrying reads is always safe. Writes, not so much.

3. All of the above

**Comment by mceachen** [comment]
I've done 2., which means we see a nice error message:

```
  1) ExifTool
       exiftool({ ignoreShebang: false })
         deleteAllTags
           issue #119:
     Error: Warning: ICC_Profile deleted. Image colors may be affected - /tmp/f5b3de32/test/delete-test.jpg
      at WriteTask.parser (src/ExifToolTask.ts:16:15)
      at WriteTask._Task_resolve (node_modules/batch-cluster/src/Task.ts:144:38)
```

**Comment by mceachen** [comment]
Fixed in 160e2fc12fd0c0aee1f4683a9f0204f6cfaab30e

**Comment by rolanday** [comment]
Thanks, Matt! Super helpful & responsive, and appreciate the change to provide a hook for caller to weigh in on if the error is worthy of an exception or not. Works great. My bad for not mentioning the ICC profile error -- I also saw the same but figured unrelated so not worth mentioning. Again, thank you!!

**Comment by mceachen** [comment]
ICYMI, I released with this fix, too. Thanks for making an easy-to-follow bug report!

Cheers. :beers:
