### ISSUE TITLE
Better documentation on resource hygiene

### ISSUE THREAD

**Issue by Mangatt** [photostructure/exiftool-vendored.js#120]
It would be great to have more detailed documentation on resource hygiene.

I think that current state is quite confusing, because:

- we should always use only one singleton, but:
- we should always end() it after use, but:
- that rejects all subsequent requests

What is the correct procedure to use in long running app without wasting system resources and memory leaks then? Should we keep this one instance active for entire lifetime of app, should we create new one for each request and end it immediatelly after use or is there other recommended approach?

**Comment by mceachen** [comment]
> we should always end() it after use

No. You should only call `end()`  when your application shuts down.

> What is the correct procedure to use in long running app without wasting system resources and memory leaks then? 

Just use the singleton when you need it. 

Any idle child process will automatically be shut down gracefully to minimize memory consumption. New child processes are spawned when demand warrants. 

Details are in the ExifTool and BatchCluster configuration settings—everything is configurable.
