### ISSUE TITLE
Bug: jest and vendored-exiftool doesn't seem to like each other

### ISSUE THREAD

**Issue by samip5** [photostructure/exiftool-vendored.js#128]
**Describe the bug**
For unknown reason, I'm getting the `Vendored ExifTool does not exist` error despite it existing at `/usr/src/app/node_modules/exiftool-vendored.pl/bin/exiftool` on Alpine. 

**To Reproduce**
Simply importing the exiftool in a jtest will result in an error when running the test.

**Expected behavior**
I would have expected it to not error out about the exiftool not existing when it actually does.

**Environment**
 - OS and version: Alpine 3.14
 - Node.JS version 16.15.1

**Comment by mceachen** [comment]
Howdy!

I've never heard of jtest before--Google seems to think it's a java testing framework. A link to the library would have been helpful.

If `node` can't find `exiftool-vendored.pl`, that's a system setup issue--not a bug with this package.

Feel free to reopen this with a link to a repository that reproduces this issue so I can take a look into it further.

**Comment by samip5** [comment]
Unfortunately, I don't have the possibility to re-open it and it seem I had miss spelled it by one character.

It's called jest, https://jestjs.io/docs/getting-started

**Comment by mceachen** [comment]
OK, `jest` makes more sense.

I'm not doing anything exotic to find the exiftool binary--if [this line](https://github.com/photostructure/exiftool-vendored.js/blob/012402c80655fde19856e66ab811dcd542fb9044/src/ExifTool.ts#L113) fails, the dependency isn't installed, or something is actively breaking how `require` works.

**Comment by samip5** [comment]
Is it searching for the perl script (.pl) or the actual exiftool binary?

**Comment by mceachen** [comment]
> Is it searching for the perl script (.pl) or the actual exiftool binary?

dude, c'mon. Read the code.

**Comment by samip5** [comment]
Yes, I did but I'm little confused as to how it works via perl as I cannot really read perl code aka exiftool-vendored.pl.
I do get the right path to the `node_modules/exiftool-vendored.pl/bin/exiftool` which seems to be a perl executable.

I'm trying to import it as:

```ts
import { exiftool } from 'exiftool-vendored';
```

The node REPL does work:

```js
Welcome to Node.js v16.15.1.
Type ".help" for more information.
> require("exiftool-vendored.pl")
'/usr/src/app/node_modules/exiftool-vendored.pl/bin/exiftool'
```

**Comment by samip5** [comment]
Something is really wierd as this does make the tests pass:

```ts
import exiftool from 'exiftool-vendored.pl';
```
