### ISSUE TITLE
Asynchronous operations that weren't stopped

### ISSUE THREAD

**Issue by ElielGez** [photostructure/exiftool-vendored.js#155]
**Describe the bug**
Noticed while trying to write tests in jest there is warning about asynchronous operations that weren't stopped.
![image](https://github.com/photostructure/exiftool-vendored.js/assets/24525253/9d324a7e-900e-4700-abc8-2592f42e5e0b)

**To Reproduce**
![image](https://github.com/photostructure/exiftool-vendored.js/assets/24525253/2b96be3b-893e-499c-af78-2cd3ec1336f9)

**Expected behavior**
To not have async operations running after the promise resolved

**Environment (please complete the following information):**
 - OS and version: Mac OS 13.5.2
 - Node.JS version 16

**Comment by mceachen** [comment]
https://github.com/photostructure/exiftool-vendored.js#mocha-v400

**Comment by ElielGez** [comment]
Sorry about that..
Thanks for the answer
