### ISSUE TITLE
GPSLatitude and GPSLongitude differs from GPSPosition

### ISSUE THREAD

**Issue by waclaw66** [photostructure/exiftool-vendored.js#165]
**Describe the bug**
Tags GPSLatitude and GPSLongitude don't match GPSPosition extracted using exiftool-vendored 24.2.0 from the picture below
```
  GPSLatitude: 37.6186111111111,
  GPSLongitude: 112.160555555556,
  GPSPosition: '37.6186111111111 -112.160555555556',
```

exiftool 12.70 shows...
`$exiftool -c "%+f" -EXIF:GPS -GPSLatitude -GPSLongitude -GPSPosition`
```
GPS Latitude                    : +37.618611
GPS Longitude                   : -112.160556
GPS Position                    : +37.618611, -112.160556
```

[20140530_125154_HDR](https://github.com/photostructure/exiftool-vendored.js/assets/15554561/e44fcc1a-ce35-41d8-81d7-9b94adcc263c)

**To Reproduce**
Just use the example snippet for reading tags.

**Expected behavior**
`GPSLongitude` should be `-112.160555555556`

**Environment (please complete the following information):**
 - Fedora 39
 - Node.JS v20.10.0

**Comment by mceachen** [comment]
That is a fantastic shot of Bryce!

Thanks for taking the time to report this.

First off, here's this library's code for extracting latitude and longitude:

https://github.com/photostructure/exiftool-vendored.js/blob/f111cda241cdca7978501ed522f986b7e6281dcb/src/ReadTask.ts#L195

You'll see I look at the "GPSLongitudeRef" value to know when the value needs to be negated. If the ref is West, I force it to negative, and if it's East, I force it to a positive value.

Your file has a negative longitude with an East ref, which I haven't seen in the wild before. 

Given that recent versions of ExifTool have been giving the proper signed values for GPS lat/lon, I think it's reasonable to remove the `Math.abs()` call [here](https://github.com/photostructure/exiftool-vendored.js/blob/f111cda241cdca7978501ed522f986b7e6281dcb/src/ReadTask.ts#L229).

Do you concur?

**Comment by waclaw66** [comment]
Perfect, thanks for a quick fix!

**Comment by waclaw66** [comment]
Seems it affects xmp sidecar files as well. https://github.com/immich-app/immich/issues/6580

**Comment by mceachen** [comment]
This new issue is a different situation and behavior from the first. In the future, please open a new issue.

This library is passing through the value it's getting from ExifTool. I'm seeing "East" as the `GPSLongitudeRef`, so there's nothing I can do from my side--I don't have access to the "raw" values, so I can't (and feel like I **really shouldn't**) add an additional "workaround" like the first issue.

There are several handfuls of bug reports in the ExifTool forum around this issue, along with remediations: 

https://exiftool.org/forum/index.php?topic=10163.msg52950#msg52950

https://exiftool.org/forum/index.php?topic=14943.msg80546#msg80546

**Comment by waclaw66** [comment]
> This library is passing through the value it's getting from ExifTool. I'm seeing "East" as the `GPSLongitudeRef`

I'm sorry, I haven't realized that "East" value comes from exiftool itself. Will check it first with `exiftool` next time. Thanks.

**Comment by mceachen** [comment]
No worries--I appreciate the time you took to gather a simple reproduction for me.

(And if you discover there's some more proper heuristic I should apply, or exiftool magick arg I should use, I'm all ears!)
