### ISSUE TITLE
inferTimezoneFromDatestamps does not detect UTC/Z/+00:00 timezones

### ISSUE THREAD

**Issue by stephanvane** [photostructure/exiftool-vendored.js#179]
**Describe the bug**
When reading an xmp file, the timezone can succesfully be extracted using the following code:

```typescript
await exiftool.read(path, undefined, { inferTimezoneFromDatestamps: true })
```

The result looks something like this:

```javascript
{
  SourceFile: 'file.xmp',
  errors: [],
  tz: 'UTC+3',
  tzSource: 'CreationDate',
  ExifToolVersion: 12.82,
  ...
```

But when the timezone is UTC, we don't get this information:

```javascript
{
  SourceFile: 'file.xmp',
  errors: [],
  ExifToolVersion: 12.82,
  ...
```

**To Reproduce**
The files used to reproduce these results are:

returns `UTC+3`:
```xml
<?xpacket begin='﻿' id='W5M0MpCehiHzreSzNTczkc9d'?>
<x:xmpmeta xmlns:x='adobe:ns:meta/' x:xmptk='Image::ExifTool 12.78'>
<rdf:RDF xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#'>

 <rdf:Description rdf:about=''
  xmlns:pdf='http://ns.adobe.com/pdf/1.3/'>
  <pdf:CreationDate>2021-12-21T02:35:00.000+03:00</pdf:CreationDate>
 </rdf:Description>
</rdf:RDF>
</x:xmpmeta>
<?xpacket end='w'?>
```

returns nothing:

```xml
<?xpacket begin='﻿' id='W5M0MpCehiHzreSzNTczkc9d'?>
<x:xmpmeta xmlns:x='adobe:ns:meta/' x:xmptk='Image::ExifTool 12.78'>
<rdf:RDF xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#'>

 <rdf:Description rdf:about=''
  xmlns:pdf='http://ns.adobe.com/pdf/1.3/'>
  <pdf:CreationDate>2021-12-21T00:35:00.000Z</pdf:CreationDate>
 </rdf:Description>
</rdf:RDF>
</x:xmpmeta>
<?xpacket end='w'?>
```

**Expected behavior**
I would expect that the second example would return:

```javascript
{
  SourceFile: 'file.xmp',
  errors: [],
  tz: 'UTC',
  tzSource: 'CreationDate',
  ExifToolVersion: 12.82,
  ...
```

**Environment (please complete the following information):**
 - OS and version: Mac OS X 14.1.1
 - Node.JS version `v20.10.0`

**Comment by mceachen** [comment]
This is actually behaving as expected: many popular smartphones and camera manufacturers erroneously mark non-time-zone-specific timestamps with a Z suffix (perhaps because the engineers didn’t know what Z meant?).

You’re certainly free to wrap read() with your own code to add additional heuristics!
