### ISSUE TITLE
Perl not installed error

### ISSUE THREAD

**Issue by Circuit8** [photostructure/exiftool-vendored.js#182]
Hi there. I'm running into an issue with exiftool-vendored versions 22 and above on Mac and Linux in Electron. When attempting to use exiftool v26 I get the following error:

```
Perl must be installed. Please add Perl to your $PATH and try again.
exiftool-vendored/src/ExifTool.ts:169:11
```

Looks like it's to do with the introduction of `which("perl")`.

Downgrading to version 21 solves the issue.

Exiftool-vendored: v22-26
OS: Ubuntu 22 & Mac 12.6
Node: v20.x
Electron: v29.x

Let me know if you need any more info. Thanks again for the great work with exiftool-vendored.

**Comment by prantikseal** [comment]
facing the same error, worked in version 21 thanks

**Comment by mceachen** [comment]
```
mrm@m1 test % node
Welcome to Node.js v20.13.1.
Type ".help" for more information.
> require("exiftool-vendored").exiftool.version().then(console.dir)
Promise {
  <pending>,
  [Symbol(async_id_symbol)]: 105,
  [Symbol(trigger_async_id_symbol)]: 90
}
> '12.84'
```

C'mon guys. If you open a bug, at least provide some sort of reproduction.

**Comment by Circuit8** [comment]
Apologies for not providing a reproduction. `26.1.0` has seemed to fix the issue though, thanks for that.
