### ISSUE TITLE
Built package contains a 107mb `snyk-linux` file

### ISSUE THREAD

**Issue by ldiqual** [photostructure/exiftool-vendored.js#200]
Version 28.2.0

https://www.npmjs.com/package/exiftool-vendored?activeTab=code

<img width="793" alt="image" src="https://github.com/user-attachments/assets/1e8d9177-1937-42f1-b4dc-da7870cd0bf1">

**Comment by mceachen** [comment]
Thanks for the heads-up: it was in my `.gitignore` (which I thought npm adopted, but I guess only if `.npmignore` is missing?).
