### ISSUE TITLE
Support Samsung's Image_UTC_Data TimeStamp

### ISSUE THREAD

**Issue by C-Otto** [photostructure/exiftool-vendored.js#209]
**Is your feature request related to a problem? Please describe.**
I have photos taken with a Samsung phone (SM-G930F, Galaxy S7) that only include the correct timezone offset if GPS was working correctly at the time of taking the photo. In other cases, the timezone offset is still contained in the file's metadata, but sadly not in any of the standard places currently supported by exiftool-vendored.

Note: this is NOT related to the "GPS to location/IANA timezone" feature.

**Describe the solution you'd like**
I'd like exiftool-vendored to parse the TimeStamp tag (in Image_UTC_Data) and make use of this point in time to adjust the offset of the (correct) local time made available in the other (standard) tags.

**Describe alternatives you've considered**
I implemented a workaround in Immich, but I guess it should rather be in exiftool-vendored.
https://github.com/immich-app/immich/pull/12712

**Additional context**
Two photos taken just seconds apart, one with GPS, one without:
![20161017_094043](https://github.com/user-attachments/assets/7b479a04-9d0f-4dee-9ac1-7af5f93ab980)
![20161017_094051](https://github.com/user-attachments/assets/a0a648cc-6813-4fcb-82f0-ed87dde83b23)

```
$ exiftool 20161017_094043.jpg | grep 2016
File Name                       : 20161017_094043.jpg
Modify Date                     : 2016:10:17 09:40:43
Date/Time Original              : 2016:10:17 09:40:43
Create Date                     : 2016:10:17 09:40:43
Time Stamp                      : 2016:10:17 16:40:43.891+02:00
Create Date                     : 2016:10:17 09:40:43.0821
Date/Time Original              : 2016:10:17 09:40:43.0821
Modify Date                     : 2016:10:17 09:40:43.0821
```

```
$ exiftool 20161017_094051.jpg | grep 2016
File Name                       : 20161017_094051.jpg
Modify Date                     : 2016:10:17 09:40:51
Date/Time Original              : 2016:10:17 09:40:51
Create Date                     : 2016:10:17 09:40:51
GPS Date Stamp                  : 2016:10:17
Time Stamp                      : 2016:10:17 16:40:51.376+02:00
Create Date                     : 2016:10:17 09:40:51.0333
Date/Time Original              : 2016:10:17 09:40:51.0333
Modify Date                     : 2016:10:17 09:40:51.0333
GPS Date/Time                   : 2016:10:17 14:40:51Z
```

Note that +02:00 is my current timezone. As such, the photos were taken at 14:40 UTC. The local time of 09:40 then makes this 09:40-05:00 (which is the expected Peru Standard Time).

**Comment by mceachen** [comment]
@C-Otto thanks for taking the time to assemble these examples and explain the situation.

Unfortunately, it seems that the "+02:00" is coming from your local system timezone.

This is what I see:

```sh
$ ls -l /etc/localtime 
lrwxrwxrwx 1 root root 39 Sep 16 17:01 /etc/localtime -> /usr/share/zoneinfo/America/Los_Angeles
```
(My workstation is set to `America/Los_Angeles`, which is currently `-07:00`.

```sh
$ exiftool -TimeStamp -j ~/Downloads/367626777-a0a648cc-6813-4fcb-82f0-ed87dde83b23.jpg
```
```json
[{
  "SourceFile": "/home/mrm/Downloads/367626777-a0a648cc-6813-4fcb-82f0-ed87dde83b23.jpg",
  "TimeStamp": "2016:10:17 07:40:51.376-07:00"
}]
```

So, I don't quite know how to proceed--I'm happy to entertain solutions, but know that defaulting to the system timezone has proven to be problematic in the past, as _people travel_.

**Comment by C-Otto** [comment]
It's a bit more complicated than it seems. You're right, I'm in +02:00 and that's what's shown. However, the crucial information is that the time WITH timezone is absolute, i.e. it contains a lot of information and this information can be used for comparisons (earlier/later/...). The usual (EXIF standard) times do NOT contain any timezone information, which makes it impossible to compare the photo's time to any other photo's time.

Even though the derived timezone is always the local one (+02:00 in my case, -07:00 in your case), you can normalize this time to UTC and, thus, get around the issue of whatever "local" is.

The real magic is cominbing the timestamp (A) that does NOT have a timezone with the absolute timestamp (B) that is shown using the local timezone offset. This way, you can derive the offset of timestamp A.

In my example, this helps from bumping the information from "at 09:40 anywhere on the world" to "at 09:40 with offset -05:00 (for example Chile)", because the timezone difference between 09:40 and 16:40+02:00 is -05:00.

**Comment by C-Otto** [comment]
Thank you :)
