### ISSUE TITLE
RAW photos (CR2, RAF): Image dimensions returned from preview

### ISSUE THREAD

**Issue by C-Otto** [photostructure/exiftool-vendored.js#218]
**Describe the bug**
Up front, this might as well be a bug in exiftool, or in the cameras producing the metadata. I'm interested in your opinion, maybe a fix in exiftool-vendored is the way to go.

Certain cameras produce RAW images (in CR2 and RAF formats, for example Canon EOS 30D) that include a high-res RAW photo and a low-res JPG preview. The metadata contains dimensions for both, and exiftool-vendored returns those values accordingly. In Immich, this causes confusion, as the low-res dimensions are used to operate on the high-res photo.

**To Reproduce**
Exiftool 12.57:

```
exiftool IMG_8121.CR2 |grep -e "3504\|2336\|1728\|1152"
Image Width                     : 1728
Image Height                    : 1152
Canon Image Width               : 3504
Canon Image Height              : 2336
AF Image Width                  : 3504
AF Image Height                 : 2336
Exif Image Width                : 3504
Exif Image Height               : 2336
Image Size                      : 3504x2336
```

exiftool-vendored (again, with grep):

```
  "ImageWidth": 1728,
  "ImageHeight": 1152,
  "CanonImageWidth": 3504,
  "CanonImageHeight": 2336,
  "AFImageWidth": 3504,
  "AFImageHeight": 2336,
  "ExifImageWidth": 3504,
  "ExifImageHeight": 2336,
  "ImageSize": "3504x2336",
```

The preview image has dimensions 1728x1152 (2 megapixel), the actual photo has dimensions 3504x2336 (8 megapixel).

See https://github.com/immich-app/immich/issues/13049 for more information. I can provide the file upon request and might be able to provide a RAF file showing a similar/identical issue.

**Expected behavior**
The width and height properties, especially ImageWidth and ImageHeight, return the "true" dimensions (3504x2336 in this example).

**Environment (please complete the following information):**

- Version of this library: v28.3.1
- OS and version: Linux, Debian Stable
- Node.js version: v20.18.0

**Comment by C-Otto** [comment]
Related discussions:
https://exiftool.org/forum/index.php?topic=4709.0
https://exiftool.org/forum/index.php?topic=13310.0
https://exiftool.org/forum/index.php?topic=2537.0

**Comment by mceachen** [comment]
It’s up to the consumer to determine what tags to use, but things get even murkier when you talk about RAW image formats: depending on how you “develop” the sensor data, your rasterized raw image might be different from the advertised resolution by 1-5% 

Just fyi, given that most image applications don’t update **any** width or height metadata fields, I’ve found them to not be trustworthy.
