### ISSUE TITLE
Cannot find module 'exiftool-vendored.pl' using exiftool with electron

### ISSUE THREAD

**Issue by EdenTurgeman** [photostructure/exiftool-vendored.js#47]
Building an app with electron and react and keep getting this issue when using exiftool-vendored.

I have read the previous post on the matter and tried to add exiftool-vendored.pl to my dependencies manually and this only generates the following error

![Capture](https://user-images.githubusercontent.com/12447231/56460568-38814a00-63ad-11e9-8a41-1a756b4907ea.PNG)

Also base issue
![image](https://user-images.githubusercontent.com/12447231/56460577-741c1400-63ad-11e9-8463-efbce4a3a021.png)

My package.json
`{
  "name": "photo-op",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@babel/register": "^7.4.0",
    "@material-ui/core": "^3.9.3",
    "@material-ui/icons": "^3.0.2",
    "exiftool-vendored": "^8.8.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-redux": "^7.0.2",
    "react-router": "^5.0.0",
    "react-router-dom": "^5.0.0",
    "react-scripts": "2.1.8",
    "recursive-readdir": "^2.2.2",
    "redux": "^4.0.1",
    "styled-components": "^4.2.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "electron": "electron ./src/main.js"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "electron": "^4.1.4"
  }
}`

**Comment by mceachen** [comment]
See https://github.com/photostructure/exiftool-vendored.js/wiki/FAQ#how-do-you-make-this-work-with-electron, but the actual solution will be specific to your codebase. 

If you think those instructions could be made better, I'd love suggestions or feedback!

Good luck.

**Comment by EdenTurgeman** [comment]
Instructions were updated, thank you for the quick response and code behavior change.
