### ISSUE TITLE
-stay_open mode question

### ISSUE THREAD

**Issue by przemyslawpluta** [photostructure/exiftool-vendored.js#48]
Are below essentially the same in terms of invocation? Essentially in both cases `A.` and `B.` `exiftool-vendored` is actually run in `-stay_open` mode and the only difference is ability to set custom `args` in `A.` with `exiftoolArgs`:

A. 
```js
const ExifTool = require('exiftool-vendored').ExifTool;
const exiftool = new ExifTool({exiftoolArgs: ['-stay_open', 'True', '-@', '-']}); 

(async () => {
   const meta = await exiftool.read('path/to/image.jpg');
   exiftool.end();
})();
```

B.
```js
const exiftool = require('exiftool-vendored').exiftool

(async () => {
   const meta = await exiftool.read('path/to/image.jpg');
   exiftool.end();
})();

```

Or does `-stay_open` have to be explicitly set as per `A.`?

**Comment by mceachen** [comment]
Yes, A and B are equivalent.

**Comment by mceachen** [comment]
Note that `DefaultExiftoolArgs` is exported, and you could instantiate your ExifTool instance with a spread of those defaults:

```ts
import { ExifTool, DefaultExiftoolArgs } from "exiftool-vendored"

const exiftoolArgs = [...DefaultExiftoolArgs, "something"]
const exiftool = new ExifTool({exiftoolArgs}); 
```

**Comment by przemyslawpluta** [comment]
@mceachen thank you
