### ISSUE TITLE
Extract PreviewTIFF

### ISSUE THREAD

**Issue by przemyslawpluta** [photostructure/exiftool-vendored.js#49]
At the moment depending on RAW file processed specific previews are available for extraction. Running `exiftool -preview:all nikon_d850.nef` we get 4x previous we can choose from:

```bash
Jpg From Raw -> exiftool.extractJpgFromRaw()                   
Other Image -> ?                    
Preview Image -> exiftool.extractPreview()                  
Thumbnail TIFF -> exiftool.extractThumbnail()                 
``` 
In some cases Preview is reported as `PreviewTIFF` and not as `PreviewImage` as per [Hasselblad RAW file](https://cdn.hasselblad.com/samples/B0000994.3FR) which seems to be impossible to extract via build in `extractPreview()` option but can be extracted directly with:

```bash
exiftool -PreviewTIFF -b B0000994.3FR > B0000994.JPG
```
It would be good to support this via `extractPreview`.

**Comment by mceachen** [comment]
You can use [extractBinaryTag](https://exiftool-vendored.js.org/classes/exiftool.html#extractbinarytag).

**Comment by mceachen** [comment]
By the way, I added that example image to the tag corpus that forms `Tags`, and published a new version now that has `PreviewTIFF`. Thanks for the pointer!

**Comment by przemyslawpluta** [comment]
@mceachen thanks
