### ISSUE TITLE
 Error: spawn /var/task/node_modules/exiftool-vendored.pl/bin/exiftool ENOENT

### ISSUE THREAD

**Issue by Cuneytt** [photostructure/exiftool-vendored.js#53]
exiftool can not be spawned in aws lambda environment, getting below error stack:
```
2019-07-18T14:45:17.836Z	288aa49b-491d-5394-a451-f131c125cf30	Error: spawn /var/task/node_modules/exiftool-vendored.pl/bin/exiftool ENOENT
at _errnoException (util.js:1022:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
at onErrorNT (internal/child_process.js:372:16)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

Using lambci/lambda:nodejs8.10 image (https://github.com/lambci/docker-lambda) the problem can be reproduced.
The error happens when initializing the below Metadata class 
```
export default class Metadata {

    private static tool: ExifTool = Metadata.initTool();

    public static tmpDirectory = `${tmpdir()}/metadata`;

    private static initTool(): ExifTool {
        logger.debug("initializing exiftool...");
        const tool = new ExifTool();
        tool.version().then(version => logger.info(`ExifTool version ${version}`));
        return tool;
    }

```

Thanks for the great tool

**Comment by mceachen** [comment]
I'd be willing to accept a PR that adds lambda support, as long as CI is set up to validate it.

**Comment by douglassaldana** [comment]
I have same issue using exiftool Lib, it seen that the new version of AMI en Lambda doesnt have perl installed!

**Comment by douglassaldana** [comment]
>  investigated a bit and I find that /usr/bin/perl is present in 2017.03 but not present in 2018.03. This is a bit of a letdown. I am unable to find any communication as to what exactly has changed between the two environments. All I see is a pointer to the 2018.03 Amazon Linux release notes, which does not mention anything about perl. There is no Lambda specific release notes about the differences between the versions.

**Comment by Cuneytt** [comment]
@douglassaldana is there an easy way to see what is installed on a lambda ami?

**Comment by douglassaldana** [comment]
> @douglassaldana is there an easy way to see what is installed on a lambda ami?

On your lambda function 

`exports.handler = function(event, context, callback) {
    const
    { spawn } = require( 'child_process' ),
    ls = spawn( 'ls', [ '/usr/bin' ] );

    ls.stdout.on( 'data', data => {
        console.log( `stdout: ${data}` );
    } );

    ls.stderr.on( 'data', data => {
        console.log( `stderr: ${data}` );
    } );

    ls.on( 'close', code => {
        console.log( `child process exited with code ${code}` );
    } );
};`

**Comment by Cuneytt** [comment]
@douglassaldana thank you very much for your help.

**Comment by mceachen** [comment]
Nice detective work, @douglassaldana! 

Your solution for #2 would be kinda grotty. Would a shebang of 

```
#!/usr/bin/env perl
```

work? Another option would be to explicitly run exiftool via perl. Which would be better?

**Comment by douglassaldana** [comment]
hahahhaha, yeah a lot of time invest on that.
yes, it kindy of g. and that would work.

**Comment by mceachen** [comment]
I don't have to muck with the source of exiftool if I launch it via perl. I'll see how that works.

If you'd be willing to add a note to the readme wrt the perl layers, that'd be a welcome edit.

**Comment by douglassaldana** [comment]
Cool, I'll

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Cuneytt** [comment]
@mceachen will it not be a lot of change to launch exiftool directly through perl? not sure but even if exiftool is called through perl directly will not the shebang line
```
#!/usr/bin/perl -w
```
cause any problem?

**Comment by mceachen** [comment]
Shebangs are ignored when scripts are run by the interpreter (they are considered a comment). It's only the shell that looks at it when executed directly.

**Comment by Cuneytt** [comment]
Using 
```
#!/usr/bin/env perl
```
as the shebang line does not work, causes 
```
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
```
```
#!/opt/bin/perl -w
```
works

**Comment by Cuneytt** [comment]
sed to replace the shebang line
```
sed -i "1 s/^.*$/#\!\/opt\/bin\/perl -w'/" path_to_exiftool
```

**Comment by mceachen** [comment]
`/opt/bin/perl` won't work for macOS or 99% of posix distributions.

**Comment by mceachen** [comment]
I think I've got a solution for you all. If `/usr/bin/perl` is missing on a non-windows platform, we "ignore the shebang" by running `spawn` under a shell, and ask the shell to spin up `perl` for us (so it needs to be in your `PATH`).

I've released 8.17.0 with this new option, which you can set explicitly in the constructor args, as well.

**Comment by Cuneytt** [comment]
Unfortunately the fix in version 8.17 seems not to be working 
Here is the simple lambda test used to verify the fix:
```
const tool = require("exiftool-vendored").exiftool;
const fs = require('fs');

exports.handler = async (event) => {
    console.log('starting exiftool test');
    console.log('files in /opt/bin');
    fs.readdirSync('/opt/bin').forEach(file => {
        console.log(file);
    });

    let version;
    console.log(`path environment variable ${process.env.PATH}`);
    try {
        version = await tool.version();
    } catch (err) {
        console.log(err);
        return;
    }
    console.log(`exiftool is successfully initialized ${version}`);
};

```

**Comment by Cuneytt** [comment]
@douglassaldana have you got a chance to try out 8.17

**Comment by mceachen** [comment]
@Cuneytt is `/opt/bin` in your `PATH`? (Try adding `require("process").env.PATH` that to your console.log)

**Comment by Cuneytt** [comment]
The cloudwatch output below shows /opt/bin is in path and perl is in /opt/bin but still can not get the version from exiftool. 
```
START RequestId: 857ace11-5a67-41b7-b229-6427e2b846d1 Version: $LATEST
2019-07-22T15:29:31.956Z	857ace11-5a67-41b7-b229-6427e2b846d1	starting exiftool test
2019-07-22T15:29:31.968Z	857ace11-5a67-41b7-b229-6427e2b846d1	files in /opt/bin
2019-07-22T15:29:31.968Z	857ace11-5a67-41b7-b229-6427e2b846d1	bootstrap
2019-07-22T15:29:31.968Z	857ace11-5a67-41b7-b229-6427e2b846d1	config_data
2019-07-22T15:29:31.968Z	857ace11-5a67-41b7-b229-6427e2b846d1	corelist
2019-07-22T15:29:31.968Z	857ace11-5a67-41b7-b229-6427e2b846d1	cpan
2019-07-22T15:29:31.968Z	857ace11-5a67-41b7-b229-6427e2b846d1	cpanel_json_xs
2019-07-22T15:29:31.968Z	857ace11-5a67-41b7-b229-6427e2b846d1	cpanm
2019-07-22T15:29:31.968Z	857ace11-5a67-41b7-b229-6427e2b846d1	enc2xs
2019-07-22T15:29:31.968Z	857ace11-5a67-41b7-b229-6427e2b846d1	encguess
2019-07-22T15:29:31.968Z	857ace11-5a67-41b7-b229-6427e2b846d1	h2ph
2019-07-22T15:29:31.968Z	857ace11-5a67-41b7-b229-6427e2b846d1	h2xs
2019-07-22T15:29:31.968Z	857ace11-5a67-41b7-b229-6427e2b846d1	instmodsh
2019-07-22T15:29:31.968Z	857ace11-5a67-41b7-b229-6427e2b846d1	json_pp
2019-07-22T15:29:31.968Z	857ace11-5a67-41b7-b229-6427e2b846d1	json_xs
2019-07-22T15:29:31.968Z	857ace11-5a67-41b7-b229-6427e2b846d1	libnetcfg
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	perl
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	perl5.26.3
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	perlbug
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	perldoc
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	perlivp
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	perlthanks
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	piconv
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	pl2pm
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	plackup
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	pod2html
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	pod2man
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	pod2text
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	pod2usage
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	podchecker
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	podselect
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	prove
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	ptar
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	ptardiff
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	ptargrep
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	shasum
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	splain
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	xsubpp
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	zipdetails
2019-07-22T15:29:31.969Z	857ace11-5a67-41b7-b229-6427e2b846d1	path environment variable /var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin
END RequestId: 857ace11-5a67-41b7-b229-6427e2b846d1
REPORT RequestId: 857ace11-5a67-41b7-b229-6427e2b846d1	Duration: 3001.96 ms	Billed Duration: 3000 ms Memory Size: 128 MB	Max Memory Used: 32 MB	
2019-07-22T15:29:34.956Z 857ace11-5a67-41b7-b229-6427e2b846d1 Task timed out after 3.00 seconds
```

**Comment by Cuneytt** [comment]
increasing the lambda timeout to 30 seconds from the default 3 seconds displays the below error
```

19:41:05
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.

19:41:05
1: node::Abort() [/var/lang/bin/node]

19:41:05
2: 0x5593b64ca892 [/var/lang/bin/node]

19:41:05
3: v8::Utils::ReportApiFailure(char const*, char const*) [/var/lang/bin/node]

19:41:05
4: 0x5593b64cb6e5 [/var/lang/bin/node]

19:41:05
5: v8::internal::PropertyCallbackArguments::Call(void (*)(v8::PropertyCallbackInfo<v8::Array> const&)) [/var/lang/bin/node]

19:41:05
6: 0x5593b6130b68 [/var/lang/bin/node]

19:41:05
7: v8::internal::KeyAccumulator::CollectOwnPropertyNames(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) [/var/lang/bin/node]

19:41:05
8: v8::internal::KeyAccumulator::CollectOwnKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSObject>) [/var/lang/bin/node]

19:41:05
9: v8::internal::KeyAccumulator::CollectKeys(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::JSReceiver>) [/var/lang/bin/node]

19:41:05
10: v8::internal::FastKeyAccumulator::GetKeys(v8::internal::GetKeysConversion) [/var/lang/bin/node]

19:41:05
11: 0x5593b62e36c7 [/var/lang/bin/node]

19:41:05
12: v8::internal::Runtime_ForInPrepare(int, v8::internal::Object**, v8::internal::Isolate*) [/var/lang/bin/node]

19:41:05
13: 0x3c3ec48c0d85
```

**Comment by mceachen** [comment]
Do you have native libraries in your lambda?

**Comment by douglassaldana** [comment]
> @douglassaldana have you got a chance to try out 8.17?

hi, i dont use the library i was just passing by and see the error and try to help

**Comment by Cuneytt** [comment]
@mceachen isolated the testing to a simple lambda handler as mentioned in https://github.com/photostructure/exiftool-vendored.js/issues/53#issuecomment-513844775 and the only dependency is exiftool-vendored. here is the package.json:
```
{
  "name": "exiftool-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "exiftool-vendored": "8.17.0"
  }
}

```

**Comment by davisowb** [comment]
For those that stumble across this in 2026, I have this working in a nodejs.24x lambda.  The trick here is to: 

1. making perl available via a layer, I am using the publicly available ones that can be found here: https://metacpan.org/pod/AWS::Lambda::AL2023. I have been working with arn:aws:lambda:eu-west-2:445285296882:layer:perl-5-42-runtime-al2023-x86_64:3
2. Ensuring that ExifTool is setup with the correct env, here is the code I was using to get it working:
```
import { ExifTool, DefaultExifToolOptions } from "exiftool-vendored";

const exiftool = new ExifTool({
  ...DefaultExifToolOptions,
  exiftoolEnv: {
    ...process.env,
    LANG: "C.UTF-8",
    LC_ALL: "C.UTF-8",
  },
  logger: () => console,
});

/**
 * Ensure exiftool shuts down cleanly.
 */
process.on("beforeExit", async () => {
  console.log('await exiftool.end()');
  await exiftool.end();
});

export const handler = async () => {
  try {
    console.log("Running exiftool.version()...");
    const vers = await exiftool.version();
    console.log("exiftool version: ", vers);
  } catch (e) {
    console.error("exiftool.version failed:", e);
    return { ok: false, error: String(e?.message ?? e) };
  }

  return { ok: true };
};
```

If you take `exiftoolEnv` out of the options then you will see the EPIPE error reproduced:
> Function Logs:
> START RequestId: da8c8cf3-c1ec-4e88-96e0-8e0b0a6bc02b Version: $LATEST
> 2026-02-04T11:57:04.425Z	da8c8cf3-c1ec-4e88-96e0-8e0b0a6bc02b	INFO	Running exiftool.version()...
> 2026-02-04T11:57:04.447Z	da8c8cf3-c1ec-4e88-96e0-8e0b0a6bc02b	DEBUG	ProcessPoolManager.maybeSpawnProcs() started healthy child process { pid: 13 }
> 2026-02-04T11:57:04.449Z	da8c8cf3-c1ec-4e88-96e0-8e0b0a6bc02b	WARN	BatchProcess(13).onError() {
>   reason: 'stdin.error',
>   task: undefined,
>   error: write EPIPE
>       at afterWriteDispatched (node:internal/stream_base_commons:159:15)
>       at writeGeneric (node:internal/stream_base_commons:150:3)
>       at Socket._writeGeneric (node:net:966:11)
>       at Socket._write (node:net:978:8)
>       at writeOrBuffer (node:internal/streams/writable:570:12)
>       at _write (node:internal/streams/writable:499:10)
>       at Writable.write (node:internal/streams/writable:508:10)
>       at #execTask (/opt/nodejs/node_modules/batch-cluster/dist/BatchProcess.js:276:23)
>       at BatchProcess.execTask (/opt/nodejs/node_modules/batch-cluster/dist/BatchProcess.js:221:43)
>       at new BatchProcess (/opt/nodejs/node_modules/batch-cluster/dist/BatchProcess.js:116:19)
> }
> 2026-02-04T11:57:04.450Z	da8c8cf3-c1ec-4e88-96e0-8e0b0a6bc02b	WARN	BatchCluster.onStartError(): Error: write EPIPE
> 2026-02-04T11:57:04.451Z	da8c8cf3-c1ec-4e88-96e0-8e0b0a6bc02b	WARN	BatchProcess(13).terminate(): force-killing still-running child.
> 2026-02-04T11:57:04.452Z	da8c8cf3-c1ec-4e88-96e0-8e0b0a6bc02b	INFO	BatchCluster.end() { gracefully: true }
> 2026-02-04T11:57:04.452Z	da8c8cf3-c1ec-4e88-96e0-8e0b0a6bc02b	INFO	await exiftool.end()
> 2026-02-04T11:57:04.452Z	da8c8cf3-c1ec-4e88-96e0-8e0b0a6bc02b	INFO	BatchCluster.end() { gracefully: true }
> END RequestId: da8c8cf3-c1ec-4e88-96e0-8e0b0a6bc02b
> REPORT RequestId: da8c8cf3-c1ec-4e88-96e0-8e0b0a6bc02b	Duration: 38.97 ms	Billed Duration: 298 ms	Memory Size: 2048 MB	Max Memory Used: 93 MB	Init Duration: 258.81 ms	Status: error	Error Type: Runtime.ExitError

With `exiftoolEnv` setup like the code above you get this working output:

> Function Logs:
> START RequestId: 1ec90b60-5d73-4fb0-8169-9aaaf023b641 Version: $LATEST
> 2026-02-04T11:59:24.266Z	1ec90b60-5d73-4fb0-8169-9aaaf023b641	INFO	Running exiftool.version()...
> 2026-02-04T11:59:24.286Z	1ec90b60-5d73-4fb0-8169-9aaaf023b641	DEBUG	ProcessPoolManager.maybeSpawnProcs() started healthy child process { pid: 13 }
> 2026-02-04T11:59:24.461Z	1ec90b60-5d73-4fb0-8169-9aaaf023b641	TRACE	tryAssignNextTask(): task submitted { pid: 13, taskId: 2 }
> 2026-02-04T11:59:24.472Z	1ec90b60-5d73-4fb0-8169-9aaaf023b641	INFO	exiftool version:  13.47
> END RequestId: 1ec90b60-5d73-4fb0-8169-9aaaf023b641
> REPORT RequestId: 1ec90b60-5d73-4fb0-8169-9aaaf023b641	Duration: 209.59 ms	Billed Duration: 465 ms	Memory Size: 2048 MB	Max Memory Used: 110 MB	Init Duration: 255.07 ms
