### ISSUE TITLE
Add Caption-Abstract IPTC tag

### ISSUE THREAD

**Issue by rawpixel-vincent** [photostructure/exiftool-vendored.js#60]
**Is your feature request related to a problem? Please describe.**
I don't find the IPTC tag Caption-abstract in Tags https://github.com/photostructure/exiftool-vendored.js/blob/master/src/Tags.ts#L4704

**Describe the solution you'd like**
I would like to be able to read and write the Caption-Abstract IPTC tag

**Comment by mceachen** [comment]
If your file has a tag that exiftool extracts, you'll get the value. I don't filter out values, in other words.

Know that the tags interface is created by some 4,000 sample files. If a tag isn't find in that set, it won't be added to the interface, but it will still be accepted both by the read and write tasks. You'll just have to force the cast.
