### ISSUE TITLE
Slower than node-exiftool ?

### ISSUE THREAD

**Issue by digitalnature** [photostructure/exiftool-vendored.js#61]
I'm getting about 2-3x slower responses from exiftool-vendored compared to a version similar to node-exiftool, which uses streams.
Does this library use the `stay_open` flag, or do I need to pass it myself somewhere?

**Comment by mceachen** [comment]
It uses stay_open.

What node version and operating system are you using?

**Comment by mceachen** [comment]
I just re-ran the benchmarks on linux:

Using node-exiftool:
```
cd benchmark ; node index.js ../../test-images
Reading 1000 files...
exiftool: Parsing took 22268ms (22.3ms / file)
Done in 22.58s.
```

Using exiftool-vendored:
```
yarn mktags ../test-images
...
Parsing took 26260ms (3.8ms / file)
```
so, yeah, 6-7x faster on linux, and much faster than that on windows.

**Comment by mceachen** [comment]
I just noticed that someone had mis-read the comment above and thought that this project was the slower one.

For the record, 

1. `exiftool-vendored` packages a [custom, faster launcher](https://github.com/photostructure/exiftool-vendored.exe/commit/14136945ab259ffcc3ba166292a54528361433b9) specifically to make Windows launching not fight with antivirus software, and launch (much) faster. It's built from the "alternative" download artifacts from ExifTool.org.

2. [exiftool-vendored.js](https://github.com/photostructure/exiftool-vendored.js) uses `-stay_open` across a *[cluster](https://github.com/photostructure/batch-cluster.js)* of ExifTool instances, so is multi-threaded, has [tests that run on a test suite of all supported OSes and Node.JS versions](https://github.com/photostructure/exiftool-vendored.js/actions?query=workflow%3A%22Node.js+CI%22), and has [robust types](https://github.com/photostructure/exiftool-vendored.js#tags).
