### ISSUE TITLE
How to read and write XMP tags

### ISSUE THREAD

**Issue by ManuCart** [photostructure/exiftool-vendored.js#65]
Hello,

I would like to read and write XMP:CreateDate but I have this error
````
Tag 'XMP_CreateDate' is not defined
````
work great with ````AllDates````

**Comment by mceachen** [comment]
In the future, don't skip over the bug report form for this project or any project. You didn't include an example image, example code, or why you'd think that tag exists.

Please consider reading the readme and especially reviewing the Tags.ts for known field names. 

Stackoverflow is a great way to get free help.

**Comment by ManuCart** [comment]
Please Help!
Didn't find how to read XMPCreateDate
Need more exemple from your repo

**Comment by mceachen** [comment]
Please do not use issues for help requests.
