### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by ManuCart** [photostructure/exiftool-vendored.js#66]
Hi,

I want to do this `with your repo in nodejs
````
exiftool -All:All= -TagsFromFile test.jpg -DateTimeOriginal -Model -LensModel -FocalLength -ISO -ExposureTime -ShutterSpeedValue -BulbDuration -ApertureValue -FNumber -WhiteBalance -Flash test.jpg
````

And please don't tell me read the doc or search by yourself.
I didn't find anything. I really need help or please write more sample in readme
I'm a newbee

**Comment by mceachen** [comment]
> And please don't tell me read the doc or search by yourself.

This is literally just `exiftool.read("test.jpg")`.

**Comment by ManuCart** [comment]
Why you close imediately the ticket?
It's not solve for me
You did not read the question
I need remove all tags except some
How to do this

**Comment by mceachen** [comment]
Please see the code for `ExifTool.deleteAllTags`. https://github.com/photostructure/exiftool-vendored.js/blob/master/src/ExifTool.ts#L363

You'll want `exiftool.write("test.jpg", {}, ["-All:All=", "-DateTimeOriginal -Model -LensModel -FocalLength -ISO -ExposureTime -ShutterSpeedValue -BulbDuration -ApertureValue -FNumber -WhiteBalance -Flash".split(" ")])`

To reiterate, Github issues are to report bugs or suggest features. Please don't use it as a help forum. Please consider using stackoverflow.com or any other site.

**Comment by ManuCart** [comment]
Thanks for your help, it's really usefull.
I'm not sure help forums or other stackoverflow do really something for me.
You are the one because you write the code.
It's more usefull for everyone to find answers in your repo than other place.
Please consider this : on other github project we use issues as a knowledge base too
