### ISSUE TITLE
Write EPIPE error thrown when moving from Node 8.10 to Node 10 or 12

### ISSUE THREAD

**Issue by mischuler** [photostructure/exiftool-vendored.js#69]
**Describe the bug**
BatchProcess throws error when trying to invoke ExifTool when running on AWS Lambda. The code executed when I was on a Node 8.10 environment but throws an error (when `setLogger` is used) on newer Node versions. My original comment is [here](https://github.com/photostructure/exiftool-vendored.js/issues/56) but I thought a separate thread would be appropriate since I can replicate in a smaller package.

> START RequestId: 6b6034af-5fa1-46f7-9f51-e3ef345becb3 Version: $LATEST
> 2019-12-03T00:55:20.244Z	6b6034af-5fa1-46f7-9f51-e3ef345becb3	INFO	Set the logger
> 2019-12-03T00:55:20.284Z	6b6034af-5fa1-46f7-9f51-e3ef345becb3	INFO	Before await
> 2019-12-03T00:55:20.465Z	6b6034af-5fa1-46f7-9f51-e3ef345becb3	WARN	2019-12-03T00:55:20.386Z | warn  | BatchProcess(19).onError() { source: 'stdin.error',
>   task: '-ver\n-ignoreMinorErrors\n-execute\n',
>   error:
>    Error: stdin.error: write EPIPE
>        at BatchProcess.onError (/var/task/node_modules/batch-cluster/dist/BatchProcess.js:368:21)
>        at Socket.<anonymous> (/var/task/node_modules/batch-cluster/dist/BatchProcess.js:75:57)
>        at Socket.emit (events.js:198:13)
>        at errorOrDestroy (internal/streams/destroy.js:107:12)
>        at onwriteError (_stream_writable.js:436:5)
>        at onwrite (_stream_writable.js:461:5)
>        at _destroy (internal/streams/destroy.js:49:7)
>        at Socket._destroy (net.js:614:3)
>        at Socket.destroy (internal/streams/destroy.js:37:8)
>        at WriteWrap.afterWrite [as oncomplete] (net.js:791:10) }
> 2019-12-03T00:55:20.565Z	6b6034af-5fa1-46f7-9f51-e3ef345becb3	WARN	2019-12-03T00:55:20.564Z | warn  | Task.reject() { cmd: '-ver\n-ignoreMinorErrors\n-execute\n',
>   error:
>    write EPIPE
>        at WriteWrap.afterWrite [as oncomplete] (net.js:789:14) }
> 2019-12-03T00:55:20.566Z	6b6034af-5fa1-46f7-9f51-e3ef345becb3	WARN	2019-12-03T00:55:20.566Z | warn  | BatchCluster.onStartError(): Error: stdin.error: write EPIPE
> END RequestId: 6b6034af-5fa1-46f7-9f51-e3ef345becb3
> REPORT RequestId: 6b6034af-5fa1-46f7-9f51-e3ef345becb3	Duration: 1335.08 ms	Billed Duration: 1400 ms	Memory Size: 128 MB	Max Memory Used: 82 MB	Init Duration: 160.24 ms

	
**To Reproduce**
The code, image, and overall package can be found in the following: 
[exiftool-vend-lambda.zip](https://github.com/photostructure/exiftool-vendored.js/files/3914000/exiftool-vend-lambda.zip)

Note: I am using a Lambda layer for perl. This is deployed in `/opt/bin` and is part of the library path. I used `ignoreShebang` for this reason.
```
exports.handler = async event => {
  const ExifTool = require("exiftool-vendored").ExifTool;
  const Logger = require("batch-cluster").Logger;
  const setLogger = require("batch-cluster").setLogger;
  
  const exiftool = new ExifTool({ignoreShebang: true});

  console.log("Set the logger");
  setLogger(
    Logger.withLevels(
      Logger.withTimestamps(
        Logger.filterLevels(
          {
            // tslint:disable: no-unbound-method
            trace: console.log,
            debug: console.warn,
            info: console.warn,
            warn: console.warn,
            error: console.error
          },
          "trace"
        )
      )
    )
  );

  // TODO implement
  console.log("Before await");
  await exiftool
    .read("./sample.jpg")
    .then((tags /*: Tags */) =>
      console.log("Make: ${tags.Make}, Model: ${tags.Model}")
    )
    .catch(err => console.error("Something terrible happened: ", err))
    .then(() => exiftool.end());
  console.log("after await");
  const response = {
    statusCode: 200,
    body: JSON.stringify("Hello from Lambda!")
  };
  console.log("Before return");
  return response;
};
```

**Expected behavior**
Execution without errors:

> START RequestId: 30cd1585-1d19-4648-8a5a-46790a70c165 Version: $LATEST
> 2019-12-03T00:47:14.354Z	30cd1585-1d19-4648-8a5a-46790a70c165	Set the logger
> 2019-12-03T00:47:14.354Z	30cd1585-1d19-4648-8a5a-46790a70c165	Before await
> 2019-12-03T00:47:16.019Z	30cd1585-1d19-4648-8a5a-46790a70c165	Make: Google, Model: Pixel 3
> 2019-12-03T00:47:16.237Z	30cd1585-1d19-4648-8a5a-46790a70c165	after await
> 2019-12-03T00:47:16.237Z	30cd1585-1d19-4648-8a5a-46790a70c165	Before return
> END RequestId: 30cd1585-1d19-4648-8a5a-46790a70c165
> REPORT RequestId: 30cd1585-1d19-4648-8a5a-46790a70c165	Duration: 1884.22 ms	Billed Duration: 1900 ms	Memory Size: 128 MB	Max Memory Used: 93 MB	

**Environment (please complete the following information):**
 - AWS Lambda [runtime link information](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)
 - Node.JS 12.13.0 or 10.16.3
- Perl 5.30

**Comment by bthiban** [comment]
I have the same issue.

**Comment by mceachen** [comment]
Thanks for the comprehensive bug report! 👍 

This looks like bugus error handling within batch cluster during close, and should hopefully be easy to repro in a test. I'll try to look into this tomorrow.

**Comment by mischuler** [comment]
You're welcome! Node 8.10LTS is being phased out from AWS Lambda so that might be why you're seeing an uptick in the question. I also have a small update.

Please let me know if I can help replicate any part of the Lambda environment.

I've tried running the "test" several times in a row, and it's bouncing back and forth between the error I've pasted above and the one below. I've tested the perl command in the index.js and it executes:

```
console.log(`path environment variable ${process.env.PATH}`);
  
  const exec = require("child_process");
    
  exec("perl -version", (err, stdout, stderr) => {
      if (err) {
        console.log("Perl not working!!");
        return;
      }
      // the *entire* stdout and stderr (buffered)
      console.log(`stdout: ${stdout}`);
      console.log(`stderr: ${stderr}`);
    });
```

> START RequestId: b500705e-ef36-4935-b398-2d7fe8bbf080 Version: $LATEST
> 2019-12-03T14:34:57.881Z	b500705e-ef36-4935-b398-2d7fe8bbf080	INFO	path environment variable /var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin
> 2019-12-03T14:34:57.903Z	b500705e-ef36-4935-b398-2d7fe8bbf080	INFO	Set the logger
> 2019-12-03T14:34:57.903Z	b500705e-ef36-4935-b398-2d7fe8bbf080	INFO	Before await
> 2019-12-03T14:34:57.963Z	b500705e-ef36-4935-b398-2d7fe8bbf080	INFO	stdout: 
> This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux-thread-multi
> 
> Copyright 1987-2019, Larry Wall
> 
> Perl may be copied only under the terms of either the Artistic License or the
> GNU General Public License, which may be found in the Perl 5 source kit.
> 
> Complete documentation for Perl, including FAQ lists, should be found on
> this system using "man perl" or "perldoc perl".  If you have access to the
> Internet, point your browser at http://www.perl.org/, the Perl Home Page.
> 
> 2019-12-03T14:34:57.963Z	b500705e-ef36-4935-b398-2d7fe8bbf080	INFO	stderr: 
> 2019-12-03T14:34:58.003Z	b500705e-ef36-4935-b398-2d7fe8bbf080	WARN	2019-12-03T14:34:58.003Z | info  | onStderr(23):/bin/sh: perl: command not found
> 2019-12-03T14:34:58.274Z	b500705e-ef36-4935-b398-2d7fe8bbf080	WARN	2019-12-03T14:34:58.274Z | warn  | _end({"gracefully":false,"source":"onExit(exit)"}) { cmd: '-ver\n-ignoreMinorErrors\n-execute\n',
>   error:
>    Error: end() called before task completed
>        at BatchProcess.<anonymous> (/var/task/node_modules/batch-cluster/dist/BatchProcess.js:287:45)
>        at step (/var/task/node_modules/batch-cluster/dist/BatchProcess.js:33:23)
>        at Object.next (/var/task/node_modules/batch-cluster/dist/BatchProcess.js:14:53)
>        at fulfilled (/var/task/node_modules/batch-cluster/dist/BatchProcess.js:5:58) }
> 2019-12-03T14:34:58.282Z	b500705e-ef36-4935-b398-2d7fe8bbf080	WARN	2019-12-03T14:34:58.282Z | warn  | BatchCluster.onStartError(): Error: end() called before task completed
> END RequestId: b500705e-ef36-4935-b398-2d7fe8bbf080
> REPORT RequestId: b500705e-ef36-4935-b398-2d7fe8bbf080	Duration: 423.47 ms	Billed Duration: 500 ms	Memory Size: 128 MB	Max Memory Used: 88 MB

**Comment by mceachen** [comment]
This is an issue with batch-cluster. `Batch.Process.onError()` now doesn't propagate errors if the process is already shutting down.

I don't have a lambda setup locally (and I'm not a huge fan of AWS, TBH), so hopefully this will resolve your issue.

I'm releasing this new version now. Please re-open if this didn't resolve this issue.

**Comment by mischuler** [comment]
Appreciate the quick responses. Unfortunately, I'm still getting a similar error after re-installing and getting the newest version of `batch-cluster (5.9.1)`.

I've pasted errors I've seen below on Lambda and locally on Windows. Is there anything I can do to further debug the process? Going back to normal Exiftool without your date/time heuristics is ... less than appealing.

The code is the same as the previously attached zip, minus the updated `node_modules`.

Error Lambda:
> START RequestId: 3ffe2b76-bfc7-4252-912d-43e6401c7663 Version: $LATEST
> 2019-12-06T18:32:27.555Z	3ffe2b76-bfc7-4252-912d-43e6401c7663	INFO	path environment variable /var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin
> 2019-12-06T18:32:27.594Z	3ffe2b76-bfc7-4252-912d-43e6401c7663	INFO	Set the logger
> 2019-12-06T18:32:27.595Z	3ffe2b76-bfc7-4252-912d-43e6401c7663	INFO	Before await
> 2019-12-06T18:32:27.654Z	3ffe2b76-bfc7-4252-912d-43e6401c7663	WARN	2019-12-06T18:32:27.654Z | info  | onStderr(20):/bin/sh: perl: command not found
> 2019-12-06T18:32:27.739Z	3ffe2b76-bfc7-4252-912d-43e6401c7663	INFO	stdout: 
> This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux-thread-multi
> 
> Copyright 1987-2019, Larry Wall
> 
> Perl may be copied only under the terms of either the Artistic License or the
> GNU General Public License, which may be found in the Perl 5 source kit.
> 
> Complete documentation for Perl, including FAQ lists, should be found on
> this system using "man perl" or "perldoc perl".  If you have access to the
> Internet, point your browser at http://www.perl.org/, the Perl Home Page.
> 
> 2019-12-06T18:32:27.739Z	3ffe2b76-bfc7-4252-912d-43e6401c7663	INFO	stderr: 
> 2019-12-06T18:32:27.910Z	3ffe2b76-bfc7-4252-912d-43e6401c7663	WARN	2019-12-06T18:32:27.907Z | warn  | _end({"gracefully":false,"source":"onExit(exit)"}) { cmd: '-ver\n-ignoreMinorErrors\n-execute\n',
>   error:
>    Error: end() called before task completed
>        at BatchProcess.<anonymous> (/var/task/node_modules/batch-cluster/dist/BatchProcess.js:287:45)
>        at step (/var/task/node_modules/batch-cluster/dist/BatchProcess.js:33:23)
>        at Object.next (/var/task/node_modules/batch-cluster/dist/BatchProcess.js:14:53)
>        at fulfilled (/var/task/node_modules/batch-cluster/dist/BatchProcess.js:5:58) }
> 2019-12-06T18:32:27.911Z	3ffe2b76-bfc7-4252-912d-43e6401c7663	WARN	2019-12-06T18:32:27.911Z | debug | BatchProcess(20).onError() post-end (expected and not propagated) { source: 'stdin.error',
>   _error:
>    Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
>        at doWrite (_stream_writable.js:411:19)
>        at writeOrBuffer (_stream_writable.js:399:5)
>        at Socket.Writable.write (_stream_writable.js:299:11)
>        at Socket.Writable.end (_stream_writable.js:584:10)
>        at Socket.end (net.js:545:31)
>        at /var/task/node_modules/batch-cluster/dist/BatchProcess.js:294:107
>        at Object.map (/var/task/node_modules/batch-cluster/dist/Object.js:8:26)
>        at /var/task/node_modules/batch-cluster/dist/BatchProcess.js:294:59
>        at Object.tryEach (/var/task/node_modules/batch-cluster/dist/Error.js:24:17)
>        at BatchProcess.<anonymous> (/var/task/node_modules/batch-cluster/dist/BatchProcess.js:293:33),
>   task: undefined }
> 2019-12-06T18:32:27.915Z	3ffe2b76-bfc7-4252-912d-43e6401c7663	WARN	2019-12-06T18:32:27.915Z | warn  | BatchCluster.onStartError(): Error: end() called before task completed
> END RequestId: 3ffe2b76-bfc7-4252-912d-43e6401c7663
> REPORT RequestId: 3ffe2b76-bfc7-4252-912d-43e6401c7663	Duration: 637.43 ms	Billed Duration: 700 ms	Memory Size: 448 MB	Max Memory Used: 87 MB	Init Duration: 164.95 ms	

Error Windows through a very simple function to call the index.
test.js
```
var test = require("./index").handler
test({});

```


> C:\Users\mischuler\Desktop\amazonlinux2\exiftool-vend-lambda>node --version
> v12.13.0
> 
> C:\Users\mischuler\Desktop\amazonlinux2\exiftool-vend-lambda>node test.js
> path environment variable C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Perl64\site\bin;C:\Perl64\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python27\;C:\Python27\Scripts;C:\Python37\Scripts\;C:\Python37\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Users\mischuler\AppData\Local\Microsoft\WindowsApps;C:\ProgramData\chocolatey\bin;C:\Program Files\Amazon\AWSCLI\bin\;C:\Program Files\nodejs\;C:\Users\mischuler\.windows-build-tools\python27\;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\mischuler\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Users\mischuler\AppData\Roaming\npm\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Python37\Scripts\;C:\Python37\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Users\mischuler\AppData\Local\Microsoft\WindowsApps;C:\ProgramData\chocolatey\bin;C:\Program Files\Amazon\AWSCLI\bin\;C:\Program Files\nodejs\;C:\Users\mischuler\AppData\Local\GitHubDesktop\bin;C:\Users\mischuler\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\mischuler\AppData\Roaming\npm
> Set the logger
> Before await
> 2019-12-06T18:58:00.154Z | info  | onStderr(21912):Unrecognized character \x90; marked by <-- HERE after MZ<-- HERE near column 3 at C:\Users\mischuler\Desktop\amazonlinux2\exiftool-vend-lambda\node_modules\exiftool-vendored.exe\bin\exiftool.exe line 1.
> 
> 2019-12-06T18:58:00.417Z | warn  | _end({"gracefully":false,"source":"onExit(exit)"}) {
>   cmd: '-ver\n-ignoreMinorErrors\n-execute\n',
>   error: Error: end() called before task completed
>       at BatchProcess.<anonymous> (C:\Users\mischuler\Desktop\amazonlinux2\exiftool-vend-lambda\node_modules\batch-cluster\dist\BatchProcess.js:287:45)
>       at step (C:\Users\mischuler\Desktop\amazonlinux2\exiftool-vend-lambda\node_modules\batch-cluster\dist\BatchProcess.js:33:23)
>       at Object.next (C:\Users\mischuler\Desktop\amazonlinux2\exiftool-vend-lambda\node_modules\batch-cluster\dist\BatchProcess.js:14:53)
>       at fulfilled (C:\Users\mischuler\Desktop\amazonlinux2\exiftool-vend-lambda\node_modules\batch-cluster\dist\BatchProcess.js:5:58)
> }
> 2019-12-06T18:58:00.420Z | debug | BatchProcess(21912).onError() post-end (expected and not propagated) {
>   source: 'stdin.error',
>   _error: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
>       at doWrite (_stream_writable.js:427:19)
>       at writeOrBuffer (_stream_writable.js:415:5)
>       at Socket.Writable.write (_stream_writable.js:305:11)
>       at Socket.Writable.end (_stream_writable.js:594:10)
>       at Socket.end (net.js:574:31)
>       at C:\Users\mischuler\Desktop\amazonlinux2\exiftool-vend-lambda\node_modules\batch-cluster\dist\BatchProcess.js:294:107
>       at Object.map (C:\Users\mischuler\Desktop\amazonlinux2\exiftool-vend-lambda\node_modules\batch-cluster\dist\Object.js:8:26)
>       at _b (C:\Users\mischuler\Desktop\amazonlinux2\exiftool-vend-lambda\node_modules\batch-cluster\dist\BatchProcess.js:294:59)
>       at Object.tryEach (C:\Users\mischuler\Desktop\amazonlinux2\exiftool-vend-lambda\node_modules\batch-cluster\dist\Error.js:24:17)
>       at BatchProcess.<anonymous> (C:\Users\mischuler\Desktop\amazonlinux2\exiftool-vend-lambda\node_modules\batch-cluster\dist\BatchProcess.js:293:33) {
>     code: 'ERR_STREAM_DESTROYED'
>   },
>   task: undefined
> }
> 2019-12-06T18:58:00.455Z | warn  | BatchCluster.onStartError(): Error: end() called before task completed

**Comment by mceachen** [comment]
FWIW this error is different: it looks like you're trying to run on windows without a perl installed.
 
What's the new error stack from lambda with 5.9.1? (also, the new version of et is stuck in [npm hell, for some reason](https://twitter.com/mrm/status/1203027196614340608))

**Comment by mceachen** [comment]
Looking at your first error, it looks the same: stdout is seeing the result of what looks to be `perl --version`. That's not right.

**Comment by mischuler** [comment]
Right. That's what's coming out of Lambda on Node12.

I went back and took a look at running 8.10 vs 12. AWS has a different underlying image runtime for 8 and 12 which I understand is out of your control. The interesting thing I'm seeing is that 8.10 (the working version) is showing perl 5.16 on the `perl -version` , which is unexpected, When I run it on Node12 (the new runtime), it shows perl 5.30 which is what I have installed in my layer.

I was confident that I had perl correctly in my layer as the version command works correctly. However, seeing how 8.10 runs, and shows a different version which I surmise AWS provides, I'm not so sure.

Is there any area where having perl in `/opt/bin` rather than `/bin/sh` would be an issue, assuming the `ignoreShebang` is used?

Node8.10
> START RequestId: 2585d77c-3bff-4f5f-87a9-6287f0c9aa2d Version: $LATEST
> 2019-12-06T19:39:16.342Z	2585d77c-3bff-4f5f-87a9-6287f0c9aa2d	path environment variable /var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin
> 2019-12-06T19:39:16.379Z	2585d77c-3bff-4f5f-87a9-6287f0c9aa2d	Set the logger
> 2019-12-06T19:39:16.398Z	2585d77c-3bff-4f5f-87a9-6287f0c9aa2d	Before await
> 2019-12-06T19:39:16.477Z	2585d77c-3bff-4f5f-87a9-6287f0c9aa2d	stdout: 
> This is perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi
> (with 39 registered patches, see perl -V for more detail)
> 
> Copyright 1987-2012, Larry Wall
> 
> Perl may be copied only under the terms of either the Artistic License or the
> GNU General Public License, which may be found in the Perl 5 source kit.
> 
> Complete documentation for Perl, including FAQ lists, should be found on
> this system using "man perl" or "perldoc perl".  If you have access to the
> Internet, point your browser at http://www.perl.org/, the Perl Home Page.
> 
> 
> 2019-12-06T19:39:16.478Z	2585d77c-3bff-4f5f-87a9-6287f0c9aa2d	stderr: 
> 2019-12-06T19:39:17.141Z	2585d77c-3bff-4f5f-87a9-6287f0c9aa2d	Make: Google, Model: Pixel 3
> 2019-12-06T19:39:17.181Z	2585d77c-3bff-4f5f-87a9-6287f0c9aa2d	after await
> 2019-12-06T19:39:17.181Z	2585d77c-3bff-4f5f-87a9-6287f0c9aa2d	Before return
> END RequestId: 2585d77c-3bff-4f5f-87a9-6287f0c9aa2d
> REPORT RequestId: 2585d77c-3bff-4f5f-87a9-6287f0c9aa2d	Duration: 1091.82 ms	Billed Duration: 1100 ms	Memory Size: 448 MB	Max Memory Used: 90 MB	Init Duration: 2.47 ms


Node12:

> START RequestId: d68068c5-4be1-4337-adb9-da60c1dcb78c Version: $LATEST
> 2019-12-06T19:45:29.246Z	d68068c5-4be1-4337-adb9-da60c1dcb78c	INFO	path environment variable /var/lang/bin:/usr/local/bin:/usr/bin/:/bin:/opt/bin
> 2019-12-06T19:45:29.283Z	d68068c5-4be1-4337-adb9-da60c1dcb78c	INFO	Set the logger
> 2019-12-06T19:45:29.300Z	d68068c5-4be1-4337-adb9-da60c1dcb78c	INFO	Before await
> 2019-12-06T19:45:29.380Z	d68068c5-4be1-4337-adb9-da60c1dcb78c	WARN	2019-12-06T19:45:29.380Z | info  | onStderr(20):/bin/sh: perl: command not found
> 2019-12-06T19:45:29.443Z	d68068c5-4be1-4337-adb9-da60c1dcb78c	INFO	stdout: 
> This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux-thread-multi
> 
> Copyright 1987-2019, Larry Wall
> 
> Perl may be copied only under the terms of either the Artistic License or the
> GNU General Public License, which may be found in the Perl 5 source kit.
> 
> Complete documentation for Perl, including FAQ lists, should be found on
> this system using "man perl" or "perldoc perl".  If you have access to the
> Internet, point your browser at http://www.perl.org/, the Perl Home Page.

**Comment by mceachen** [comment]
Sorry, but at this point I just have no interest in supporting lambda.

* there's no easy way for CI tests to be added (that I know of)
* due to numerous reasons, I have no interest in patronizing or supporting AWS 
* the "ignoreShebang" feature was built as a "hail Mary", without being able to test it on lambda proper, which means I can't/won't support it

Sorry!

**Comment by mcmoood** [comment]
@mischuler Hi, I have the exact same issue when moving lambda from NodeJs 8 to 10. Do you have a work around for this issue?

**Comment by mischuler** [comment]
@mcmoood I couldn't figure anything out, and I spent a good amount of time with AWS support as well.

I used the tool for metadata extraction and proper importing of timezones, so I tried my best to mimic the heuristics in place in the code and just calling exiftool directly. 

It's not as robust as the mechanisms Matthew has implemented, but I get by.
