### ISSUE TITLE
URL for homepage 404

### ISSUE THREAD

**Issue by Circuit8** [photostructure/exiftool-vendored.js#70]
Visiting https://exiftool-vendored.js.org/ is giving a 404 error. Not sure if you already know this or not!

![Screenshot from 2020-01-20 13-10-34](https://user-images.githubusercontent.com/6171759/72728875-45260f00-3b86-11ea-889b-c825ceed6603.png)

**Comment by mceachen** [comment]
Thanks. As I don't own the .js.org domain, in the interest of reducing security totals, I switched to https://photostructure.github.io/exiftool-vendored.js/ (but didn't update the top link, which I did just now).

Thanks for the heads-up!
