### ISSUE TITLE
read returning ExifDate instead of ExifDateTime for DateTimeOriginal and CreateDate tags

### ISSUE THREAD

**Issue by rolanday** [photostructure/exiftool-vendored.js#71]
**Describe the bug**
For [file linked](https://www.dropbox.com/s/900lhp5xemsh3kw/HASSELBLAD-HASSELBLADH5D-50C.FFF?dl=0), read is returning tags object where DateTimeOriginal and CreateDate properties are ExifDate objects (instead of ExifDateTime), and hence no time info.

file link: https://www.dropbox.com/s/900lhp5xemsh3kw/HASSELBLAD-HASSELBLADH5D-50C.FFF?dl=0

**To Reproduce**
Please include sample code, and a sample image, which reproduces the bug

**Code Sample**:
```javascript
const exiftool = require("exiftool-vendored").exiftool;
const path = './HASSELBLAD-HASSELBLADH5D-50C.FFF';
exiftool.read(path).then((tags) => {
    console.log(`I am an ${tags.DateTimeOriginal.constructor.name} instance.`);
});

// outputs: "I am an ExifDate instance."
```

**package.json**:
```json
{
  "name": "exiftool.experimental",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "exiftool-vendored": "^9.6.0"
  }
}
```

**Expected behavior**
Expecting an ExifDateTime object, as running ExifTool on the same file returns both date and time.

```bash
$ exiftool -s ./HASSELBLAD-HASSELBLADH5D-50C.FFF | grep -i datetime
DateTimeOriginal                : 2015-11-14T14:20:36
```

**Environment (please complete the following information):**
 - Mac OS X 10.16.2
 - Node.JS version 12.13.1

**Comment by mceachen** [comment]
First off: thanks for the perfect bug report. :star::star::star::star::star:

I've always seen EXIF timestamps in this format:  `2015:11:14 14:20:36`

However, your file is using ISO formatting for the DateTimeOriginal:

```
$ exiftool -j ~/Desktop/HASSELBLAD-HASSELBLADH5D-50C.FFF | grep -i date
  "FileModifyDate": "2020:02:13 09:59:16-08:00",
  "FileAccessDate": "2020:02:13 11:02:29-08:00",
  "FileInodeChangeDate": "2020:02:13 09:59:21-08:00",
  "ModifyDate": "2015:11:14 14:20:36",
  "DateTimeOriginal": "2015-11-14T14:20:36",
  "CreateDate": "2015-11-14T14:20:36",
```

I don't see how adding ISO parsing support could possibly break things. I'll add it now. (also, feel free to remove your example file from your dropbox if you need to save storage space)

(funny that we need to transfer 80,127,010 bytes to see

**Comment by mceachen** [comment]
(also, you should totally try PhotoStructure)

**Comment by rolanday** [comment]
Thanks for the quick turn-around!! I'll try out the change and report back.

Again, super appreciate the responsiveness and your exiftool-vendored.js contribution in general. Great work!

-Roland.
