### ISSUE TITLE
xmpMM:DerivedFrom from the Tags definition 

### ISSUE THREAD

**Issue by woss** [photostructure/exiftool-vendored.js#74]
**Describe the bug**
I've been looking to get the `DerivedFrom*` tags and when i use the interface `Tags` it is not there but it is in the output.

**To Reproduce**
```
import { exiftool, Tags } from 'exiftool-vendored';

function readImportantTags(b: Tags): void {
  console.log('DerivedFrom', b.DerivedFrom); // Property 'DerivedFrom' does not exist on type 'Tags'.ts(2339)
}
```

**Expected behavior**
See the `DerivedFrom` in the autocomplete list

**Environment (please complete the following information):**
not important

**Comment by mceachen** [comment]
The `Tags` interface is generated from some >6000 actual sample images with metadata. If none of those files have a tag, it won't show up in the interface, but you can cast the tags object to an `any` if you want access, if you know it's there.

I've never seen these `DerivedFrom*` tags, btw: where are they from? Can you share an example file?

**Comment by woss** [comment]
> I've never seen these DerivedFrom* tags, btw: where are they from? Can you share an example file?
 that is very strange since they are in the standard, described as 
![Capture](https://user-images.githubusercontent.com/80440/78278323-293fd180-7516-11ea-9dd0-37664cbf33d7.JPG)

Also when i read them via `readRaw` they appear as well as with the `read` method.
```
// readRaw()
DerivedFromInstanceID: 'xmp.iid:dc....,
DerivedFromDocumentID: 'xmp.did:dc....,
DerivedFromOriginalDocumentID: '.....',


// read()

"DerivedFrom": {
    "DocumentID": "xmp.did:dc...",
    "InstanceID": "xmp.iid:dc....",
    "OriginalDocumentID": "...."
},
```

**Comment by woss** [comment]
this one should have it https://www.flickr.com/photos/dwoss/49711651371

**Comment by woss** [comment]
and it seems that we are kinda competitors 😁, I'm building https://sensio.group/sensio-photo

**Comment by mceachen** [comment]
@woss pull requests welcomed, even from competitors

**Comment by woss** [comment]
you've said that tags are generated so can i add anything to the Tags? Or dod you have in mind a different approach. 

what would be the best way to contact you? Our main concentration point is in building this https://www.sensio.group/sensio-network  and because of you being the developer and a person who is building photo oriented software i was thinking if we could have a chat and see does how SensioNetwork can solve some of the problems that you have and maybe be useful in your project.  ping me on keybase (woss) when you can

**Comment by mceachen** [comment]
FWIW these tags already handled correctly, they just aren't in the types.

```js
> const e = require("exiftool-vendored")
> e.exiftool.read("../test-images/important/49711651371_18900d62c8_o.jpg").then(ea => console.dir(ea.DerivedFrom))
Promise { <pending> }
> {
  DocumentID: 'xmp.did:dc336491-3ad3-d14d-b6d5-09674661b15f',
  InstanceID: 'xmp.iid:dc336491-3ad3-d14d-b6d5-09674661b15f',
  OriginalDocumentID: 'C4CEBFD8B6A782A5E0DC32AFE31D6D09'
}
```

See `ApplicationRecordTags` for an example of manually-injected tag types. If you wanted to add another interface similar to that, I'd be open to a PR.
