### ISSUE TITLE
BatchCluster has ended, cannot enqueue

### ISSUE THREAD

**Issue by urthling** [photostructure/exiftool-vendored.js#75]
I'm running into intermittent issues in a Google Cloud Function - for example, using a singleton in an async function:

```
await exiftool
		.version()
		.then((version) =>
		{
			// testing...
			return console.log(`We're running ExifTool v${version}`)
		})
		.catch((err) => console.error("Something bad happened with exiftool version check: ", err))
```

And here's there error:

> BatchCluster has ended, cannot enqueue -ver
> -ignoreMinorErrors
> -execute
> 
>     at BatchCluster.enqueueTask (/srv/node_modules/batch-cluster/dist/BatchCluster.js:225:25)
>     at /srv/node_modules/exiftool-vendored/dist/ExifTool.js:318:83
>     at Object.<anonymous> (/srv/node_modules/exiftool-vendored/dist/AsyncRetry.js:48:42)
>     at step (/srv/node_modules/exiftool-vendored/dist/AsyncRetry.js:33:23)
>     at Object.next (/srv/node_modules/exiftool-vendored/dist/AsyncRetry.js:14:53)
>     at /srv/node_modules/exiftool-vendored/dist/AsyncRetry.js:8:71
>     at new Promise (<anonymous>)
>     at __awaiter (/srv/node_modules/exiftool-vendored/dist/AsyncRetry.js:4:12)
>     at g (/srv/node_modules/exiftool-vendored/dist/AsyncRetry.js:42:34)
>     at Object.<anonymous> (/srv/node_modules/exiftool-vendored/dist/AsyncRetry.js:54:47)

What am I missing?

**Comment by mceachen** [comment]
GCF is very likely incompatible with any process that forks, which is required to run exiftool.

You could try a different NPM library that uses exiv2, but that will require native binaries to be compiled for GCF.

Good luck.

**Comment by urthling** [comment]
Ahh.. gotcha, much appreciate the fast response!

I'm also using ur tool outside of a google function -- excellent work sir

**Comment by counterbeing** [comment]
I just ran into the same issue with AWS Lambda. I suppose it won't work there either? It's odd to me, because I've read about some other folks managing to get exiftool running in a lambda layer somehow. 

@mceachen do you think it's possible to get this working in a lambda layer? 

I'm going to keep tinkering with it and see where I get.

But also want to say thanks for such a nice tool where one was missing. Installing exiftool was always an annoying extra step.

**Comment by mceachen** [comment]
@counterbeing There are several other closed issues that may have pointers to helping you with Lambda, but know that batch-cluster (which this library relies on) wasn't designed for an environment that prohibits forking.

**Comment by bnjmnrsh** [comment]
I've also encountered this while trying to extract data from images as part of an Astro component during a static build. I have reverted to generating and saving all data in a JSON object, which I traverse as part of a pre-compile step.
