### ISSUE TITLE
Writing metadata tags to PNG image fails on Linux

### ISSUE THREAD

**Issue by sujeetsinha** [photostructure/exiftool-vendored.js#82]
I have an ExpressJS based application which provides API endpoints for certain operations. I use this library for several XMP based tasks. Everything works fine when I'm executing the code on my Windows machine. However, once I deploy the code to a Google AppEngine (which is based on Linux, I've verified), the code breaks for PNG images having color depth of 16-bit. Everything else works fine. On further investigation, it seems it doesn't fail for all 16-bit files but only ones which have chromaticity coordinates set.

Below is the code snippet I'm using to write the metadata:
```
exiftool.write(filepath, { Subject: JSON.parse(metadata) }, ["-overwrite_original"])
.then(() => {
    console.log('Meta tags updated');
})
.catch(err => {
    console.error("Something terrible happened with putting meta tags: ", err);
});
```

The error I get is as follows:

> Something terrible happened with putting meta tags: Error: Temporary file already exists: /app/server/uploads/test image.png_exiftool_tmp
> at WriteTask.parser (/app/node_modules/exiftool-vendored/dist/ExifToolTask.js:66)
> at WriteTask.<anonymous> (/app/node_modules/batch-cluster/dist/Task.js:122)
> at step (/app/node_modules/batch-cluster/dist/Task.js:33)
> at Object.next (/app/node_modules/batch-cluster/dist/Task.js:14)
> at (/app/node_modules/batch-cluster/dist/Task.js:8)
> at Promise (<anonymous>)
> at __awaiter (/app/node_modules/batch-cluster/dist/Task.js:4)
> at WriteTask.Task.resolve (Task.js:116)
> at BatchProcess.<anonymous> (/app/node_modules/batch-cluster/dist/BatchProcess.js:489)
> at step (/app/node_modules/batch-cluster/dist/BatchProcess.js:33)

Node v10 is used for both my Windows machine and AppEngine environment.
Exiftool npm version: upgraded from 9.5.0 to 12.0.0, but issue present for both the versions.

[Sample file from Wikipedia](https://upload.wikimedia.org/wikipedia/commons/b/b0/CIExy1931.png)

Can someone please advise?

**Comment by sujeetsinha** [comment]
[Sample file that I found on Wikipedia](https://upload.wikimedia.org/wikipedia/commons/b/b0/CIExy1931.png)

**Comment by mceachen** [comment]
The error is self-explanatory. The temp file exists.

Also, as CI cannot validate correctness, proprietary platforms like Google AppEngine are not supported.

**Comment by sujeetsinha** [comment]
Hi @mceachen, I ensured that there is no temp file at the specified path, even checking the existence of any file before the `exiftool.write()`. Same issue was reproduced on a VM running Linux.

**Comment by mceachen** [comment]
Sorry, I can't reproduce this with your example code:

```
> et.write("./test.png", {Subject: "hello world 1"}, ["-overwrite_original"]).then(console.log)
Promise { <pending> }
> undefined
> et.write("./test.png", {Subject: "hello world 2"}, ["-overwrite_original"]).then(console.log)
Promise { <pending> }
> undefined
> et.write("./test.png", {Subject: "hello world 3"}, ["-overwrite_original"]).then(console.log)
Promise { <pending> }
> undefined
```
(no problems, and after each command, I verified that the file's metadata had been correctly updated). 


If I had to guess, I'd bet it's due to race conditions in your server. Use unique filenames per request (rather than `/app/server/uploads/test image.png`): add something (like a counter) to ensure each filename is unique.

If you're still having issues, perhaps try removing the `["-overwrite_original"]` arg and manage files yourself.
