### ISSUE TITLE
Question: How to replace all tags in one pass and write to a target folder?

### ISSUE THREAD

**Issue by BananaAcid** [photostructure/exiftool-vendored.js#93]
Hi, I am trying to use the tool to remove all tags and add a few copyright tags instead, for 2000-4000 images to new location.

It seems there have to be multiple steps to achieve that ?
- exif: removeAllTags() -> renames original file and creates a new one
- exif: write() .. new tags to new file (again a write call)
- node: move file to new location
- node: rename the renamed file back to the original name
- * 3000

Is there a better way? 

In particular combining removeAllTags and write to a single file access and selecting a specific path to write to?

**Comment by mceachen** [comment]
>Is there a better way?

Absolutely: I'd just directly use `exiftool`: it great (and fast) for doing exactly this sort of large scale recursive operations. Just make sure you have a backup of your source images before you start.

There are many examples of doing this sort of tag stripping in the exiftool forum. [Here's the command you want](https://exiftool.org/forum/index.php?topic=2117.msg9282#msg9282).
