### ISSUE TITLE
Question: Tags from different groups / not mentioned in docs

### ISSUE THREAD

**Issue by BananaAcid** [photostructure/exiftool-vendored.js#94]
Hi, the tags.ts shows different interfaces for the different tag groups, the example
`exiftool.write("path/to/file.jpg", { XPComment: "this is a test comment" })` shows no "group" to use ... how is it specified to what to set?

For example setting "Copyright" for 
1. `EXIF - 0x8298 | Copyright` 
2. `IPTC - 116 | CopyrightNotice`
3. `PNG - 'Copyright' | Copyright` 

Any ideas or hints for me? You might want to extend the `readme.md` to include infos on this.

**Comment by mceachen** [comment]
> how is it specified to what to set?

The write tags are exactly equivalent to calls to `exiftool`, so `write("path/to/file.jpg", {Copyright: "John Doe"}` will result in -Copyright="John Doe".

write("path/to/file.jpg", {"EXIF:Copyright": "John Doe"}` will result in `-EXIF:Copyright="John Doe"` which is what I think you want.

> You might want to extend the readme.md to include infos on this.

Done!
