### ISSUE TITLE
Feature: flag to overwrite on `.write()`, optionally specifying a target

### ISSUE THREAD

**Issue by BananaAcid** [photostructure/exiftool-vendored.js#95]
Hi, `.write()` always creates a new file and renames to old one, appending `_original` to a file, like `test.JPG_original`.

1. It would be great, to have a flag to overwrite the modified file. 
2. It would be helpful to specify a target.

**Comment by mceachen** [comment]
If you'd like to provide a pull request for this that includes tests, feel free to submit it, and I'll be happy to review it. 👍

**Comment by BananaAcid** [comment]
I think, this did the trick
```
await ExifTool.write(newTarget, { ...tags}, ['-overwrite_original']);
```


It did NOT seem to work with
```
const exiftool = new ExifTool({ exiftoolArgs: ['-overwrite_original'] });
await ExifTool.write(newTarget, { ...tags}); // awaits forever
```

Questions: 
1. The working one: Does the "stay_open" still work when adding params to `write()`?
2. Do you know why the second block did not work? [DefaultExifToolOptions + constructor options L239](https://github.com/photostructure/exiftool-vendored.js/blob/main/src/ExifTool.ts#L239)


Maybe worth mentioning in the readme.md ;)

**Comment by hossam-96** [comment]
Where I can find the list of arguments I can pass like "overwrite_original" ?

**Comment by mceachen** [comment]
https://exiftool.org/#running
