### ISSUE TITLE
Question: Is it possible to write metadata to a file without loading the complete file in the memory?

### ISSUE THREAD

**Issue by sujeetsinha** [photostructure/exiftool-vendored.js#96]
Hi, I've been using this NPM package successfully for my application and getting all desired outcomes. But, ran into a problem recently and was not successful in finding a solution in the documentation, so reaching out.

My application is running in GCP App Engine (I'm aware that you are not actively supporting cloud platforms) but the server is set to 512MB of RAM (per server instance) as per current usage. Recently, there have been a need to process large files (earlier it was max size of 100MB per file and now the requirement shot upto 1GB per file). When I tried a sample file, I see the App Engine instance gets restarted due to memory usage exceeding the threshold. So, my question is that do we have a flag/param to say write metadata to a file without loading the complete file (equivalent of a fast read, if my understanding of that process is correct). I want to keep my memory usage under 512MB when processing a file larger than the RAM size.

**Comment by mceachen** [comment]
This is an ExifTool usage question. Please ask on their [forum](https://exiftool.org/forum) or on stackoverflow.
