### ISSUE TITLE
Support file buffer as input

### ISSUE THREAD

**Issue by JakobJingleheimer** [photostructure/exiftool-vendored.js#97]
**Is your feature request related to a problem? Please describe.**

In many cases, the file may already be read and loaded into memory (ex the buffer returned by node's fs.readFile) and, in addition to updating EXIF data, other operations will happen.

**Describe the solution you'd like**

If the file input is a buffer, use that and resolve with the modified buffer.

**Describe alternatives you've considered**

Sharp, but that is very slow because it needlessly re-compresses the image (because that's what it's supposed to do).

**Additional context**

None

**Comment by mceachen** [comment]
See https://github.com/photostructure/exiftool-vendored.js/issues/84

**Comment by JakobJingleheimer** [comment]
Ahh, sorry I searched "buffer" but not "stream" (I figured "memory" would be too ambiguous).
