### ISSUE TITLE
Add ability to extract thumbnails as base64

### ISSUE THREAD

**Issue by przemyslawpluta** [photostructure/exiftool-vendored.js#99]
**Is your feature request related to a problem? Please describe.**
Add ability to extract thumbnails as base64

**Describe the solution you'd like**
As exiftool supports ability to extract binary data from file as base64 it would be good to add an option similar to e.g. `exiftool.extractJpgFromRawBase64("path/to/image.cr2", "path/to/fromRaw.json")` where extracted thumbnail is base64

**Describe alternatives you've considered**
There does not appear to be a way to pass required command directly via vendored version e.g. `exiftool -preview:JpgFromRaw "path/to/image.cr2" -b -json -w "path/to/fromRaw.json"` which would produce json file with preview available as base64

**Additional context**
none

**Comment by przemyslawpluta** [comment]
If we could have a new set of options e.g. `extractThumbnailBase64`, `extractPreviewBase64`, `extractJpgFromRawBase64` or use existing flow with additional parameter e.g. `exiftool.extractJpgFromRaw("base64", "path/to/image.cr2", "path/to/fromRaw.jpg")` it looks like all it would be required is addition of **-json** to [args](https://github.com/photostructure/exiftool-vendored.js/blob/c5a6b9c3ed0649f7f98df1e1607ce67b8a438cda/src/BinaryExtractionTask.ts#L22) to generate JSON file which contains base64 content.

**Comment by przemyslawpluta** [comment]
Using `exiftool.extractBinaryTag("json", "path/to/image.cr2", "path/to/image.json");` produces JSON file with `JpgFromRaw` base64 content but also includes all available tags which are not required.

**Comment by mceachen** [comment]
1c7fa0d20fd515f29b9cc3ba3886feafebc3e644 implements `ExifTool.extractBinaryTagToBuffer`, released with version 15.0.0.

**Comment by przemyslawpluta** [comment]
@mceachen Thanks.

With `base64` outcome in some cases we'll end up with images in incorrect orientation and I wonder if there would be a way to change the orientation and get correct base64 outcome without defaulting to: 

1. `exiftool.extractJpgFromRaw("path/to/image.cr2", "path/to/image.jpg")`
2. `exiftool.write("path/to/image.jpg", {Orientation: 'Rotate 270 CW'}, ['-overwrite_original_in_place'])`
3. then generate `base64` outside of `exiftool` with correctly oriented image "path/to/image.jpg"

which would require disk I/O ...

**Comment by mceachen** [comment]
> we'll end up with images in incorrect orientation ... which would require disk I/O

You're correct. The stay_open mode doesn't seem to support streaming actual file contents to exiftool (but if I'm wrong, please tell me!)

**Comment by mceachen** [comment]
FWIW, I've asked for this feature to be added: https://exiftool.org/forum/index.php?topic=12619.msg68507#new
